// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.CommandBase;
import java.util.function.DoubleSupplier;
import edu.wpi.first.wpilibj.GenericHID;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import frc.robot.RobotContainer;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.DriveTrain;
import frc.robot.subsystems.NavX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class HaloDrive extends CommandBase {
    NavX navx = new NavX();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
        private final DriveTrain m_driveTrain;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


    public HaloDrive(DriveTrain subsystem) {


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_driveTrain = subsystem;
        addRequirements(m_driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
    }

    // Called every time the scheduler runs while the command is scheduled.
    
    public void drive() {




        double finesse = 1;
        double leftSpeed = RobotContainer.getInstance().getdriverController().getRawAxis(5);
        double rightSpeed = RobotContainer.getInstance().getdriverController().getRawAxis(1);

        double deadband = 0.3;
        if (Math.abs(leftSpeed) < 
        deadband)
        {
            leftSpeed = 0;
        }
        if(Math.abs (rightSpeed) < deadband)
        { 
            rightSpeed = 0;
        }
        XboxController m_hid = new XboxController(0);
        m_hid.setRumble(GenericHID.RumbleType.kBothRumble, 1.0);
            
        
            
        // This will delineratise the driving
        int exponent = 3;
        rightSpeed = Math.pow(rightSpeed , exponent);
        leftSpeed = Math.pow(leftSpeed , exponent);

            
        if (RobotContainer.getInstance().getdriverController().getXButton()){finesse = .5;}  
        leftSpeed *= finesse;
        rightSpeed *= finesse;
        m_driveTrain.driveTank(leftSpeed, rightSpeed);
    }   
    public void levelSelf()
    {
        navx.displayAxis();
        
        double pitch = (double)navx.getPitch();
        SmartDashboard.putNumber("pitch", pitch);


        double speed = (pitch/20)+0.083;
        SmartDashboard.putNumber("speed1", speed);


        SmartDashboard.putNumber("speed2", speed);


        m_driveTrain.driveTank(speed, speed);
    }

    @Override
    public void execute() {

        SmartDashboard.putBoolean("self level activated", RobotContainer.getInstance().getdriverController().getRightBumper());
        if(RobotContainer.getInstance().getdriverController().getRightBumper())
        {
            levelSelf();
        }
        else{
            drive();
        }
            
    
    }
            

            
    



    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
